package anifire.util
{
   public class UtilDictOffline
   {
      
      public static var error:Array;
      
      public static var array:UtilHashArray = buildArray();
       
      
      public function UtilDictOffline()
      {
         super();
      }
      
      public static function buildArray() : UtilHashArray
      {
         var _loc1_:UtilHashArray = new UtilHashArray();
         _loc1_.push("player_menu","Create your own animated videos like this at GoAnimate.com!");
         _loc1_.push("player_frontpromo1","created this video on");
         _loc1_.push("player_frontpromo2","This video is created on");
         _loc1_.push("player_errnotfound","The movie is not found");
         _loc1_.push("player_errdeleted","This movie has been deleted");
         _loc1_.push("player_errprivate","This movie is private. Please ask the creator to turn sharing on so that everyone can see it.");
         _loc1_.push("player_errprocess","This movie is being processed.  It will be ready shortly.");
         _loc1_.push("player_buffering","buffering...");
         _loc1_.push("player_privated","Your animation is currently private");
         _loc1_.push("player_shareit","Share it with others to earn GoPoints!");
         _loc1_.push("player_shareitnogp","Share it with others");
         _loc1_.push("player_privatesharing","*Only people you give the URL to can view your video");
         _loc1_.push("sharing_create","Create your own");
         _loc1_.push("sharing_slideshow","Slideshow");
         _loc1_.push("sharing_emessage","eMessage");
         _loc1_.push("sharing_animation","Animation");
         _loc1_.push("sharing_embed","Embed this video on your website");
         _loc1_.push("sharing_copy","Copy");
         _loc1_.push("sharing_link","Create a link to this video");
         _loc1_.push("sharing_createanimation","Create your own video");
         _loc1_.push("sharing_ongoanimate","on GoAnimate to create your own animated videos.");
         _loc1_.push("sharing_freefun","It\'s free and fun!");
         _loc1_.push("sharing_or","Or");
         _loc1_.push("sharing_registered","if you already have an account.");
         _loc1_.push("sharing_signup","Sign up");
         _loc1_.push("sharing_login","login");
         _loc1_.push("sharing_commaseparate","Separate multiple addresses with commas");
         _loc1_.push("sharing_emailout","Email this video");
         _loc1_.push("sharing_yourname","Your name");
         _loc1_.push("sharing_youremail","Your Email Address");
         _loc1_.push("sharing_friendemail","Your friends\' emails");
         _loc1_.push("sharing_select","Select Recipients");
         _loc1_.push("sharing_addall","Add all ");
         _loc1_.push("sharing_nocontacts","No contacts yet. Input them above and we automatically add them.");
         _loc1_.push("sharing_toaccess","to access your contact list");
         _loc1_.push("sharing_register","register");
         _loc1_.push("sharing_thankyou","Thank you for sharing this video. Let\'s hope your friends like it!");
         _loc1_.push("sharing_close","Close");
         _loc1_.push("sharing_autoadd","We automatically updated your contact list with the email addresses you manually entered, so that next time it can all be done in one click!");
         _loc1_.push("sharing_easylist","This list is just to make your life easier. We will under no circumstance send unsolicited email to your contacts.");
         _loc1_.push("sharing_ongoanimate","on GoAnimate and make it easier to share animations with your friends!");
         _loc1_.push("sharing_createaccount","Create an account");
         _loc1_.push("sharing_withaccount","With an account, you can create a contact list and send emails to many recipients with just a few clicks...");
         _loc1_.push("sharing_checkout","Check out");
         _loc1_.push("sharing_towatch","to watch more videos or create your own.\n\nCopy and paste the below URL in your browser");
         _loc1_.push("sharing_contactlist","Contact List");
         _loc1_.push("sharing_modifymessage","Modify our default message");
         _loc1_.push("sharing_cancel","Cancel");
         _loc1_.push("sharing_send","Send");
         _loc1_.push("sharing_defaultmessage","Hey,\n\nHa ha, check out this video I created. It\'s a little outrageous and crazy, but really funny!\n\n\"");
         _loc1_.push("sharing_errname","Please input your name");
         _loc1_.push("sharing_errmessage","Please input your message");
         _loc1_.push("sharing_erremail","Please input your friends\' email");
         _loc1_.push("sharing_errmore","Please input no more than 10 emails");
         _loc1_.push("ok","OK");
         _loc1_.push("loading","PREPARING...");
         _loc1_.push("guide_bubble_text","Add scenes to create a richer story.\n(Click to hide)");
         _loc1_.push("mainstage_displaying","Displaying:");
         _loc1_.push("mainstage_preparing","Preparing:");
         _loc1_.push("mainstage_scene","Scene");
         _loc1_.push("mainstage_import","Import:");
         _loc1_.push("mainstage_images","Images");
         _loc1_.push("mainstage_sound","Sound");
         _loc1_.push("mainstage_addscene","Add scene");
         _loc1_.push("mainstage_delscene","Delete scene");
         _loc1_.push("mainstage_autosavedone","Auto Save Complete");
         _loc1_.push("mainstage_remind_to_save","Remember to save your video!");
         _loc1_.push("topbtnbar_copy","Copy");
         _loc1_.push("topbtnbar_paste","Paste");
         _loc1_.push("topbtnbar_undo","Undo");
         _loc1_.push("topbtnbar_redo","Redo");
         _loc1_.push("topbtnbar_new","New Animation");
         _loc1_.push("topbtnbar_savenshare","Save and Share");
         _loc1_.push("topbtnbar_preview","Preview");
         _loc1_.push("topbtnbar_lastsaved","Last Saved");
         _loc1_.push("topbtnbar_mychar","My Character");
         _loc1_.push("ctrlbtnbar_flip","Flip");
         _loc1_.push("ctrlbtnbar_forward","Bring Forward");
         _loc1_.push("ctrlbtnbar_backward","Send Backward");
         _loc1_.push("ctrlbtnbar_delete","Delete");
         _loc1_.push("ctrlbtnbar_lookinto","Look into");
         _loc1_.push("ctrlbtnbar_lookout","Look out");
         _loc1_.push("ctrlbtnbar_edit","Edit");
         _loc1_.push("ctrlbtnbar_color","Customize color");
         _loc1_.push("timeline_duration","Duration");
         _loc1_.push("timeline_1sec","1 sec");
         _loc1_.push("timeline_2sec","2 secs");
         _loc1_.push("timeline_3sec","3 secs");
         _loc1_.push("timeline_4sec","4 secs");
         _loc1_.push("timeline_copy","Copy");
         _loc1_.push("timeline_delete","Delete");
         _loc1_.push("timeline_insertbefore","Insert Before");
         _loc1_.push("timeline_insertafter","Insert After");
         _loc1_.push("timeline_starttime","Start time");
         _loc1_.push("timeline_volume","Volume");
         _loc1_.push("timeline_playsound","Play sound");
         _loc1_.push("timeline_stopsound","Stop sound");
         _loc1_.push("timeline_removesound","Remove sound");
         _loc1_.push("timeline_1sc","1 scene");
         _loc1_.push("timeline_2sc","2 scenes");
         _loc1_.push("timeline_5sc","5 scenes");
         _loc1_.push("timeline_10sc","10 scenes");
         _loc1_.push("timeline_20sc","20 scenes");
         _loc1_.push("timeline_30sc","30 scenes");
         _loc1_.push("timeline_allsc","all scenes");
         _loc1_.push("timeline_soundexceed","Only 4 sounds can be played at the same time. Make sure you first select the scene where you want to add your sound.");
         _loc1_.push("timeline_durationalert","Your animation cannot be longer than 2 minutes. Remove or shorten scenes before you can make it public.");
         _loc1_.push("actionmenu_action","Actions");
         _loc1_.push("actionmenu_states","States");
         _loc1_.push("actionmenu_movement","Movement");
         _loc1_.push("actionmenu_slide","Slide");
         _loc1_.push("actionmenu_facial","Facial Expression");
         _loc1_.push("actionmenu_default","default");
         _loc1_.push("actionmenu_handheld","Hand-held");
         _loc1_.push("actionmenu_head","Head");
         _loc1_.push("actionmenu_headgear","Headgear");
         _loc1_.push("actionmenu_restoreprop","Remove Prop");
         _loc1_.push("actionmenu_restorehead","Restore Head");
         _loc1_.push("actionmenu_restoremask","Remove Mask");
         _loc1_.push("actionmenu_removeMove","Remove Movement");
         _loc1_.push("motionmenu_addpoint","Add Control Point");
         _loc1_.push("motionmenu_removepoint","Remove Control Point");
         _loc1_.push("effecttray_edit","Edit");
         _loc1_.push("effecttray_show","Show");
         _loc1_.push("effecttray_hide","Hide");
         _loc1_.push("effecttray_delete","Delete");
         _loc1_.push("assetinfo_editzoomtitle","Edit Zoom Effect");
         _loc1_.push("assetinfo_editzoomsubtitle","Modify the timing and speed of your zoom effect");
         _loc1_.push("assetinfo_editassettitle","Edit Asset");
         _loc1_.push("assetinfo_editassetsubtitle","Modify the timing of your bubble and effect");
         _loc1_.push("assetinfo_done","Done");
         _loc1_.push("assetinfo_name","Name:");
         _loc1_.push("assetinfo_tags","Tags:");
         _loc1_.push("assetinfo_public","Public");
         _loc1_.push("assetinfo_private"," Private");
         _loc1_.push("assetinfo_default"," Set as default");
         _loc1_.push("assetinfo_delete"," Delete");
         _loc1_.push("assetinfo_update"," Update");
         _loc1_.push("assetinfo_cancel"," Cancel");
         _loc1_.push("assetinfo_warning"," Please enter a valid Title");
         _loc1_.push("goalert_delprop","Delete prop");
         _loc1_.push("goalert_delbackground","Delete background");
         _loc1_.push("goalert_delsound","Delete sound");
         _loc1_.push("goalert_delcharacter","Delete character ");
         _loc1_.push("goalert_deleffect","Delete effect");
         _loc1_.push("goalert_delete","Delete");
         _loc1_.push("goalert_cancel","Cancel");
         _loc1_.push("goalert_delproptext","You will not be able to use this prop any more!");
         _loc1_.push("goalert_delbackgroundtext","You will not be able to use this background any more!");
         _loc1_.push("goalert_delsoundtext","You will not be able to use this sound any more!");
         _loc1_.push("goalert_delcharactertext","You will not be able to use this character any more!");
         _loc1_.push("goalert_deleffecttext","You will not be able to use this effect any more!");
         _loc1_.push("goalert_confirmaddhead","Add Head to My Stuff");
         _loc1_.push("goalert_add","Add");
         _loc1_.push("goalert_addwholeimage","Add whole image");
         _loc1_.push("goalert_addcropimage","Add cropped image");
         _loc1_.push("goalert_foundsamechar","We found that same character exists on other scenes, do you want to add the prop on all of them?");
         _loc1_.push("goalert_addtoall","Yes, add to all");
         _loc1_.push("goalert_thisoneonly","No, this one only");
         _loc1_.push("goalert_removesound","Please remove the sound(s) in this scene before deleting it.");
         _loc1_.push("goalert_newanimation","Are you sure to create a new animation?");
         _loc1_.push("goalert_yes ","YES");
         _loc1_.push("goalert_no","NO");
         _loc1_.push("previewwindow_save","Save Now >");
         _loc1_.push("previewwindow_back","< Back to edit");
         _loc1_.push("previewwindow_preview","Preview animation:");
         _loc1_.push("pubwin_savenshare","Save & Share");
         _loc1_.push("pubwin_savenclose","Save & Close");
         _loc1_.push("pubwin_save_signup","Sign Up & Save");
         _loc1_.push("pubwin_savensharetips","Save your animation and email it to your friends. This will close the studio.");
         _loc1_.push("pubwin_savenclosetips","Save your animation and close the studio.");
         _loc1_.push("pubwin_saveonlytips","Save and continue to edit your animation.");
         _loc1_.push("pubwin_soundfile","Sound File(*.mp3;*.wav;*.m4a)");
         _loc1_.push("pubwin_tagsub","Separate tags with commas\ne.g. comedy, romance, Angelina Jolie");
         _loc1_.push("pubwin_addnsave","Add song and save >");
         _loc1_.push("pubwin_savenosound","Save without music >");
         _loc1_.push("pubwin_psharingtips","On: Send the URL of your animation to share it. It cannot be searched on GoAnimate.\n\nOff: Only you can access your animation.");
         _loc1_.push("pubwin_soundtutotialtips","Adding sound effects, background music and even voices... \n\nit is all explained in our sound tutorial.");
         _loc1_.push("pubwin_title","Save your animation");
         _loc1_.push("pubwin_subtitle","Tell us more about your animation so that people can find it more easily");
         _loc1_.push("pubwin_movietitle","Title");
         _loc1_.push("pubwin_required","Required");
         _loc1_.push("pubwin_tags","Tags");
         _loc1_.push("pubwin_description","Description");
         _loc1_.push("pubwin_movielang","Choose your movie language");
         _loc1_.push("pubwin_movielangsub","Please help us organize your animation based on its language for better browsing experience");
         _loc1_.push("pubwin_pickthumb","Choose your thumbnail");
         _loc1_.push("pubwin_saveas","Save as");
         _loc1_.push("pubwin_public","Public");
         _loc1_.push("pubwin_private","Private");
         _loc1_.push("pubwin_psharing","Private Sharing");
         _loc1_.push("pubwin_on","On");
         _loc1_.push("pubwin_off","Off");
         _loc1_.push("pubwin_saveonly","Save Only");
         _loc1_.push("pubwin_warningtitle","Please input the title");
         _loc1_.push("pubwin_astitle","No background music? Are you sure?!");
         _loc1_.push("pubwin_assubtitle","You can add music, sound effects, and even voices to your GoAnimate animations.");
         _loc1_.push("pubwin_aslib","Add a sound from our library");
         _loc1_.push("pubwin_uploadtitle","Upload your own song");
         _loc1_.push("pubwin_import","Import Sound");
         _loc1_.push("pubwin_max","(maximum file size 8MB)");
         _loc1_.push("pubwin_browse","Browse");
         _loc1_.push("pubwin_upload","Upload");
         _loc1_.push("pubwin_importdone","Import Successful");
         _loc1_.push("pubwin_learnmore","Want to learn more");
         _loc1_.push("pubwin_watch","Watch video tutorial");
         _loc1_.push("pubwin_parent","Ask your parents to confirm your account to be able to make your animation public");
         _loc1_.push("pubwin_durationalert","Your animation is more than 2 min. Shorten it and make it public.");
         _loc1_.push("pubwin_nonactivate","Confirm your account to be able to make your animation public");
         _loc1_.push("constant_warningtitle","Please input the title");
         _loc1_.push("constant_warningtag","Please input the tag");
         _loc1_.push("constant_warningbad","Please avoid using bad language");
         _loc1_.push("constant_combo","Please select one");
         _loc1_.push("constant_error","Err, Sorry please try again later");
         _loc1_.push("constant_connecterr","Oops, a connection problem occurred. The task could not be completed. Please try again.");
         _loc1_.push("constant_disabled","This feature is disabled when you create animations with ");
         _loc1_.push("constant_othertheme","This will be enabled when you create animation using other themes.");
         _loc1_.push("thumbtray_importhead","Import Head");
         _loc1_.push("thumbtray_import","import");
         _loc1_.push("thumbtray_char","char");
         _loc1_.push("thumbtray_prop","prop");
         _loc1_.push("thumbtray_background","background");
         _loc1_.push("thumbtray_sound","sound");
         _loc1_.push("thumbtray_effect","effect");
         _loc1_.push("thumbtray_found","found");
         _loc1_.push("thumbtray_result","Results");
         _loc1_.push("thumbtray_loading","Loading...");
         _loc1_.push("thumbtray_nokey","Please input some keywords to search");
         _loc1_.push("thumbtray_nokeytitle","NO keywords");
         _loc1_.push("thumbtray_colortitle","Color changing bunnies!");
         _loc1_.push("thumbtray_colorsubtitle","You can change my colors.");
         _loc1_.push("thumbtray_coloricon","Look for this icon");
         _loc1_.push("thumbtray_colorclose","- Close tip -");
         _loc1_.push("thumbtray_headswapwarn","This feature is exclusively available when you create an animation with a GoAnimate only cast.");
         _loc1_.push("thumbtray_handheld","Hand-held");
         _loc1_.push("thumbtray_headgear","Headgear");
         _loc1_.push("thumbtray_head","Head");
         _loc1_.push("thumbtray_error","constant_error");
         _loc1_.push("thumbtray_others","Others");
         _loc1_.push("thumbtray_music","Music");
         _loc1_.push("thumbtray_meffect","Effects");
         _loc1_.push("thumbtray_mvo","Voice-overs");
         _loc1_.push("thumbtray_theme","Theme");
         _loc1_.push("thumbtray_dragtip","Drag these to the stage");
         _loc1_.push("thumbtray_search","Search");
         _loc1_.push("fontchooser_left","left");
         _loc1_.push("fontchooser_right","right");
         _loc1_.push("fontchooser_center","center");
         _loc1_.push("fontchooser_title","Font properties:");
         _loc1_.push("fontchooser_bgtitle","Background color:");
         _loc1_.push("fontchooser_align","Align:");
         _loc1_.push("fontchooser_bold","B");
         _loc1_.push("fontchooser_convert","Convert to Speech");
         _loc1_.push("cropper_changepos","Change position");
         _loc1_.push("cropper_fixpos","Fix position");
         _loc1_.push("cropper_undocrop","Undo Crop");
         _loc1_.push("cropper_crop","Crop");
         _loc1_.push("cropper_objshape","Object Shape");
         _loc1_.push("cropper_faceshape","Face Shape");
         _loc1_.push("cropper_tip1","Adjust position and size to match the semi-transparent reference.");
         _loc1_.push("cropper_tip2","Move the anchor points to match the shape of your image.\n\nClick on the lines to add anchor points.\n\nDouble click on anchor points to delete them.");
         _loc1_.push("cropper_tip3","Preview the image to upload and import it.\n\nIf you want to make modifications, click on \'Modify Crop\' to go back to the last step.");
         _loc1_.push("cropper_size","Size");
         _loc1_.push("cropper_rotate","Rotate");
         _loc1_.push("cropper_flip","Flip");
         _loc1_.push("cropper_adjustcrop","Adjust Crop Area");
         _loc1_.push("cropper_curve","Curved lines");
         _loc1_.push("cropper_straight","Straight lines");
         _loc1_.push("cropper_modcrop","Modify Crop");
         _loc1_.push("cropper_addmystuff","Add to My Stuff");
         _loc1_.push("cropper_readyimport","You\'re now ready to import your image to your library.");
         _loc1_.push("cropper_skip","Skip this step, upload whole image");
         _loc1_.push("cropper_cancel","Cancel");
         _loc1_.push("cropper_posimage","Position Image");
         _loc1_.push("propwin_customize ","Customize Color");
         _loc1_.push("propwin_restore","Restore default");
         _loc1_.push("assettool_width","Width");
         _loc1_.push("assettool_height","Height");
         _loc1_.push("nsawin_warning","Warning!");
         _loc1_.push("nsawin_title1","You are not logged in.");
         _loc1_.push("nsawin_title2","You can try our animation studio, but will not be able to save your work.");
         _loc1_.push("nsawin_tryout","Try our studio");
         _loc1_.push("nsawin_login","Login");
         _loc1_.push("nsawin_or","or");
         _loc1_.push("nsawin_signup","Sign up");
         _loc1_.push("nsawin_enable","first to enable saving your animation");
         _loc1_.push("saveprogress_upload","Uploading the animation");
         _loc1_.push("saveprogress_analysis","Analyzing the animation");
         _loc1_.push("saveprogress_saving","Saving the animation");
         _loc1_.push("saveprogress_render","Rendering the animation");
         error = ["nsawin_warning","sharing_errmessage","nsawin_error","pubwin_error","assetinfo_error","thumbtray_error","fontchooser_error","assettool_error","nsawin_error"];
         return _loc1_;
      }
   }
}
